services:
  cmbraga-service-app:
    container_name: cmbraga-service-app
    build: .
    env_file: .env
    ports:
      - "127.0.0.1:${PORT}:${PORT}"

    depends_on:
      - cmbraga-service-db
      - cmbraga-service-redis
    restart: always

  cmbraga-service-db:
    container_name: cmbraga-service-db
    env_file: .env
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes: ['cmbraga-service-db-data:/var/lib/postgresql/data']
    restart: always

  cmbraga-service-redis:
    container_name: cmbraga-service-redis
    env_file: .env
    image: redis:6.2.6-alpine
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    restart: always


volumes:
  cmbraga-service-db-data:
